### ISSUE TITLE
The path to the error log file is wrong

### ISSUE THREAD

**Issue by MLidstrom** [Starcounter/starcounter.io#135]
On the page http://starcounter.io/guides/tools/error-log/ it says that the log file folder is to be found at C:\Users\[YourName]\Starcounter\[Version]\Personal\ but it should be C:\Users\[YourName]\Documents\Starcounter\Personal

**Comment by per-samuelsson** [comment]
Yeah, that pattern recently changed. Good catch. Thanks.

**Comment by bigwad** [comment]
Perhaps then something like \<*my documents*\>\Starcounter\Personal?

**Comment by warpech** [comment]
Actually the page says: `C:\Users\[YourName]\Starcounter\[Version]\Personal\`

I assume this was wrong for much longer time, because the previous path was `C:\Users\[YourName]\**Documents**\Starcounter\[Version]\Personal\` and the current path is `C:\Users\[YourName]\**Documents**\Starcounter\Personal\`.

I have updated the text. Now it is: 

> 1. Locate the root server directory of your Starcounter installation. The default path for the personal server is: `C:\Users\[YourName]\Documents\Starcounter\Personal`.
  - In older versions of Starcounter, it was: `C:\Users\[YourName]\Documents\Starcounter\[Version]\Personal`
